tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "laishulu/macism"
tap "dracula/install"
tap "yandex/arc", "https://arc-vcs.yandex-team.ru/homebrew-tap"

brew "bat"
brew "broot"
brew "glib"
brew "cmake"
brew "python@3"
brew "cpplint"
brew "libssh2"
brew "curl"
brew "eza"
brew "fd"
brew "figlet"
brew "fontforge", link: false
brew "fzf"
brew "gh"
brew "gifsicle"
brew "git"
brew "libevent"
brew "go"
brew "imagemagick"
brew "jq"
brew "librsvg"
brew "libssh"
brew "libzip"
brew "lpeg"
brew "lua-language-server"
brew "luarocks"
brew "neovim", args: ["HEAD"]
brew "node"
brew "ripgrep"
brew "rustup-init"
brew "s3cmd"
brew "sd"
brew "wget"
brew "zoxide"
brew "laishulu/macism/macism"
brew "yandex/arc/arc-launcher"

cask "chromium"
cask "fontforge"
cask "keycastr"
cask "kitty"
cask "iterm2"
cask "linearmouse"
cask "macfuse"
cask "hiddenbar"
cask "monitorcontrol"
cask "rescuetime"
cask "alfred"
cask "transmission"
cask "bettertouchtool"
cask "appcleaner"
cask "dracula-colorslurp"
cask "disk-inventory-x"
cask "github"
cask "handbrake"


mas "Amphetamine", id: 937984704

vscode "asvetliakov.vscode-neovim"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "editorconfig.editorconfig"
vscode "github.remotehub"
vscode "github.vscode-pull-request-github"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-vsliveshare.vsliveshare"
vscode "perseus.vscode-yandex-arc"
vscode "pkief.material-icon-theme"
vscode "spadin.zmk-tools"
vscode "withfig.fig"
vscode "xabikos.javascriptsnippets"
