export AGENT_BROWSER_IDLE_TIMEOUT_MS=3600000

if [[ ! -o interactive ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.bun/bin:./node_modules/.bin:$PATH"
  return
fi

source ~/.profile

# Added by Obsidian
export PATH="$PATH:/Applications/Obsidian.app/Contents/MacOS"
