#!/usr/bin/env zsh

emulate -LR zsh
set -euo pipefail

repo_root=${0:A:h:h:h}
tmp_root=$(mktemp -d "${TMPDIR:-/tmp}/instruction-projection.XXXXXX")
trap 'rm -rf "$tmp_root"' EXIT

fixture_root="$tmp_root/repo"
home_dir="$tmp_root/home"

mkdir -p \
  "$fixture_root/ai/instructions" \
  "$fixture_root/claude" \
  "$fixture_root/codex" \
  "$fixture_root/config/opencode" \
  "$fixture_root/scripts/lib" \
  "$fixture_root/scripts/tests" \
  "$home_dir"

cp "$repo_root/scripts/lib/install-common.zsh" "$fixture_root/scripts/lib/install-common.zsh"
cp "$repo_root/scripts/lib/instruction-projection.zsh" "$fixture_root/scripts/lib/instruction-projection.zsh"

cat > "$fixture_root/ai/instructions/one.md" <<'EOF'
# One

First instruction.
EOF

cat > "$fixture_root/ai/instructions/two.md" <<'EOF'
# Two

Second instruction.
EOF

cat > "$fixture_root/config/opencode/.opencode.template.jsonc" <<'EOF'
{
  "$schema": "https://opencode.ai/config.json",
  "plugin": ["oh-my-openagent"],
  "instructions": [
    "~/.agents/instructions/stale.md"
  ],
  "provider": {
    "example": {
      "name": "Example"
    }
  }
}
EOF

fail() {
  print -u2 -- "$1"
  exit 1
}

HOME="$home_dir" zsh -c "source '$fixture_root/scripts/lib/instruction-projection.zsh'; instruction_projection_sync '$fixture_root'"

[[ -f "$fixture_root/claude/CLAUDE.md" ]] || fail "missing generated Claude file"
[[ -f "$fixture_root/config/opencode/.opencode.template.jsonc" ]] || fail "missing generated OpenCode template"
[[ -f "$fixture_root/codex/AGENTS.md" ]] || fail "missing generated Codex AGENTS"

expected_claude=$'# Глобальные инструкции\n\n@~/.agents/instructions/one.md\n@~/.agents/instructions/two.md'
actual_claude=$(< "$fixture_root/claude/CLAUDE.md")
[[ "$actual_claude" == "$expected_claude" ]] || fail "unexpected Claude imports"

actual_opencode=$(jq -c '.instructions' "$fixture_root/config/opencode/.opencode.template.jsonc")
[[ "$actual_opencode" == '["~/.agents/instructions/one.md","~/.agents/instructions/two.md"]' ]] || fail "unexpected OpenCode instructions"
[[ "$(jq -r '.provider.example.name' "$fixture_root/config/opencode/.opencode.template.jsonc")" == "Example" ]] || fail "OpenCode provider config was not preserved"

ugrep -Fq '<!-- GENERATED by scripts/build-agents-md from ai/instructions/*.md.' "$fixture_root/codex/AGENTS.md" || fail "Codex generated comment changed"
ugrep -Fq '# One' "$fixture_root/codex/AGENTS.md" || fail "Codex AGENTS missing first instruction"
ugrep -Fq '# Two' "$fixture_root/codex/AGENTS.md" || fail "Codex AGENTS missing second instruction"

HOME="$home_dir" zsh -c "source '$fixture_root/scripts/lib/instruction-projection.zsh'; instruction_projection_check '$fixture_root'"

rm "$fixture_root/ai/instructions/"*.md

if HOME="$home_dir" zsh -c "source '$fixture_root/scripts/lib/instruction-projection.zsh'; instruction_projection_check '$fixture_root'" 2>"$tmp_root/missing.err"; then
  fail "empty instruction directory was accepted"
fi

ugrep -Fq "no instruction markdown files" "$tmp_root/missing.err" || fail "empty instruction directory error message missing"

print "test-instruction-projection: ok"
