local instruction_projection_module_path=${${(%):-%N}:A}
local instruction_projection_module_dir=${instruction_projection_module_path:h}

if (( ! $+functions[die] )); then
  source "$instruction_projection_module_dir/install-common.zsh"
fi

instruction_projection_name() {
  print -r -- "${SCRIPT_NAME:-instruction-projection}"
}

instruction_projection_claude_path() {
  print -r -- "${1:A}/claude/CLAUDE.md"
}

instruction_projection_opencode_path() {
  print -r -- "${1:A}/config/opencode/.opencode.template.jsonc"
}

instruction_projection_agents_path() {
  print -r -- "${1:A}/codex/AGENTS.md"
}

instruction_projection_requirements() {
  local name

  name=$(instruction_projection_name)
  command -v jq >/dev/null 2>&1 || die "$name: missing required command: jq"
  command -v diff >/dev/null 2>&1 || die "$name: missing required command: diff"
}

instruction_projection_source_paths() {
  local root=${1:A} source_path
  local LC_ALL=C
  local -a source_paths

  source_paths=("$root"/ai/instructions/*.md(N))
  (( ${#source_paths[@]} > 0 )) || die "instruction-projection: no instruction markdown files"

  for source_path in "${source_paths[@]}"; do
    print -r -- "${source_path#$root/}"
  done
}

instruction_projection_projected_paths() {
  local root=${1:A} source_path basename

  instruction_projection_source_paths "$root" | while IFS= read -r source_path; do
    basename=${source_path:t}
    print -r -- "~/.agents/instructions/$basename"
  done
}

instruction_projection_projected_paths_json() {
  local root=${1:A}

  instruction_projection_projected_paths "$root" | jq -R -s 'split("\n") | map(select(length > 0))'
}

instruction_projection_render_claude() {
  local root=${1:A} projected_path

  print -r -- "# Глобальные инструкции"
  print
  instruction_projection_projected_paths "$root" | while IFS= read -r projected_path; do
    print -r -- "@$projected_path"
  done
}

instruction_projection_render_agents() {
  local root=${1:A} source_path
  local first=1

  {
    print -r -- "<!-- GENERATED by scripts/build-agents-md from ai/instructions/*.md."
    print -r -- "     Do not edit by hand. Re-run: ./scripts/install-mcp --sync-only -->"
    print

    instruction_projection_source_paths "$root" | while IFS= read -r source_path; do
      (( first )) || print
      cat "$root/$source_path"
      first=0
    done
  }
}

instruction_projection_render_opencode() {
  local root=${1:A}
  local opencode_path instructions_json

  opencode_path=$(instruction_projection_opencode_path "$root")
  [[ -f "$opencode_path" ]] || die "instruction-projection: missing OpenCode template: $opencode_path"

  instructions_json=$(instruction_projection_projected_paths_json "$root")
  jq --argjson instructions "$instructions_json" '.instructions = $instructions' "$opencode_path"
}

instruction_projection_write_if_changed() {
  local target_path=$1 tmp

  mkdir -p "${target_path:h}"
  tmp=$(mktemp "${TMPDIR:-/tmp}/instruction-projection.XXXXXX")
  cat > "$tmp"

  if [[ -f "$target_path" ]] && diff -q "$target_path" "$tmp" >/dev/null 2>&1; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target_path"
  fi
}

instruction_projection_check_file() {
  local target_path=$1 tmp

  tmp=$(mktemp "${TMPDIR:-/tmp}/instruction-projection-check.XXXXXX")
  cat > "$tmp"

  if [[ ! -f "$target_path" ]]; then
    rm -f "$tmp"
    die "instruction-projection: missing generated artifact: $target_path"
  fi

  if ! diff -q "$target_path" "$tmp" >/dev/null 2>&1; then
    rm -f "$tmp"
    die "instruction-projection: stale generated artifact: $target_path"
  fi

  rm -f "$tmp"
}

instruction_projection_sync_claude() {
  local root=${1:A}

  instruction_projection_requirements
  instruction_projection_render_claude "$root" \
    | instruction_projection_write_if_changed "$(instruction_projection_claude_path "$root")"
}

instruction_projection_sync_agents() {
  local root=${1:A}

  instruction_projection_requirements
  instruction_projection_render_agents "$root" \
    | instruction_projection_write_if_changed "$(instruction_projection_agents_path "$root")"
}

instruction_projection_sync_opencode() {
  local root=${1:A}

  instruction_projection_requirements
  instruction_projection_render_opencode "$root" \
    | instruction_projection_write_if_changed "$(instruction_projection_opencode_path "$root")"
}

instruction_projection_sync() {
  local root=${1:A}

  instruction_projection_sync_claude "$root"
  instruction_projection_sync_opencode "$root"
  instruction_projection_sync_agents "$root"
}

instruction_projection_check() {
  local root=${1:A}

  instruction_projection_requirements
  instruction_projection_render_claude "$root" \
    | instruction_projection_check_file "$(instruction_projection_claude_path "$root")"
  instruction_projection_render_opencode "$root" \
    | instruction_projection_check_file "$(instruction_projection_opencode_path "$root")"
  instruction_projection_render_agents "$root" \
    | instruction_projection_check_file "$(instruction_projection_agents_path "$root")"
}
